Add poetry to PATH and add user friendly checks

diff --git a/.jenkins/Jenkinsfile b/.jenkins/Jenkinsfile
--- a/.jenkins/Jenkinsfile
+++ b/.jenkins/Jenkinsfile
@@ -16,6 +16,7 @@ pipeline {
             CONDA_ENV = "$WORKSPACE/env"
             CONDA_HOME = "$HOME/miniconda"
             PATH = "$HOME/.local/bin:$PATH"
+            POETRY = "poetry"
           }
           stages {
             stage('Build environment') {
@@ -26,6 +27,13 @@ pipeline {
                   make env.conda
                   conda activate "${CONDA_ENV}"
                   conda info
+                  if ! command -v $POETRY &> /dev/null
+                  then
+                    echo "$POETRY could not be found"
+                    exit
+                  else
+                    echo "$($POETRY --version) installed at : $(which $POETRY)"
+                  fi
                 '''
               }
             }
